/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.Admin;

import Business.Course.Course;
import Business.Course.CourseDirectory;
import Business.Faculty.Professor;
import Business.Faculty.ProfessorDirectory;
import Business.Person.PersonDirectory;
import Business.Student.Student;
import Business.Student.StudentDirectory;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raisi
 */
public class AdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EmployerJPanel
     */
   private JPanel HomeJPanel;
    Professor professor;
    private ProfessorDirectory manageprofessor;
    private PersonDirectory manageperson;
    private CourseDirectory managecourse;
    private StudentDirectory managestudent;
    
    
    public AdminJPanel(JPanel HomeJPanel, ProfessorDirectory manageprofessor, CourseDirectory managecourse, StudentDirectory managestudent, PersonDirectory manageperson) {
        initComponents();
        this.HomeJPanel = HomeJPanel;
        this.manageprofessor = manageprofessor;
        this.managecourse = managecourse;
        this.manageperson = manageperson;
        this.managestudent = managestudent;
        populateProfessorAnalytics();
        populateStudentAnalytics();
        populateCourseAnalytics();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        adminLogoPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JButton();
        adminPanelLabel = new javax.swing.JLabel();
        adminPanel = new javax.swing.JPanel();
        adminTabbedPane = new javax.swing.JTabbedPane();
        AdminHomeJPanel = new javax.swing.JPanel();
        studentHomeLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AdminProfessorJPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        profAnalyticsTbl = new javax.swing.JTable();
        AdminStudentJPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        studentAnalyticsTbl = new javax.swing.JTable();
        AdminCoursesJPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        courseAnalyticsTbl = new javax.swing.JTable();

        jSplitPane1.setDividerLocation(130);
        jSplitPane1.setDividerSize(1);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        adminLogoPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cloud-campus small logo 1.png"))); // NOI18N
        jLabel1.setText("LOGO");

        logoutBtn.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(102, 51, 0));
        logoutBtn.setText("LOGOUT");
        logoutBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        logoutBtn.setContentAreaFilled(false);
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        adminPanelLabel.setBackground(new java.awt.Color(255, 255, 255));
        adminPanelLabel.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        adminPanelLabel.setForeground(new java.awt.Color(102, 51, 0));
        adminPanelLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminPanelLabel.setText("ADMIN LOGIN");

        javax.swing.GroupLayout adminLogoPanelLayout = new javax.swing.GroupLayout(adminLogoPanel);
        adminLogoPanel.setLayout(adminLogoPanelLayout);
        adminLogoPanelLayout.setHorizontalGroup(
            adminLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminLogoPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(adminPanelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );
        adminLogoPanelLayout.setVerticalGroup(
            adminLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminLogoPanelLayout.createSequentialGroup()
                .addGroup(adminLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminPanelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(adminLogoPanel);

        adminPanel.setBackground(new java.awt.Color(255, 255, 255));

        adminTabbedPane.setBackground(new java.awt.Color(255, 255, 255));
        adminTabbedPane.setForeground(new java.awt.Color(102, 51, 0));
        adminTabbedPane.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N

        AdminHomeJPanel.setBackground(new java.awt.Color(255, 255, 255));
        AdminHomeJPanel.setPreferredSize(new java.awt.Dimension(1200, 570));

        studentHomeLabel.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        studentHomeLabel.setForeground(new java.awt.Color(102, 51, 0));
        studentHomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        studentHomeLabel.setText("<html>Welcome to the Admin Portal!  Your gateway to overseeing the academic realm at Cloud University.<br>Here, you'll gain access to a comprehensive dashboard, providing valuable insights and analytics \non both our esteemed professors and dedicated students. <br>Harness the power of data to make informed decisions, nurture excellence, and shape the future of education at your fingertips. \n<br>Explore our robust features and tools to efficiently manage the academic landscape, all in one centralized hub. \n<br>Join us in fostering a learning environment where knowledge meets innovation, and possibilities are boundless.<html>");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/adminHome.png"))); // NOI18N

        javax.swing.GroupLayout AdminHomeJPanelLayout = new javax.swing.GroupLayout(AdminHomeJPanel);
        AdminHomeJPanel.setLayout(AdminHomeJPanelLayout);
        AdminHomeJPanelLayout.setHorizontalGroup(
            AdminHomeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminHomeJPanelLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(AdminHomeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminHomeJPanelLayout.createSequentialGroup()
                        .addComponent(studentHomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 1115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminHomeJPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(370, 370, 370))))
        );
        AdminHomeJPanelLayout.setVerticalGroup(
            AdminHomeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminHomeJPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(studentHomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        adminTabbedPane.addTab("Home", AdminHomeJPanel);

        AdminProfessorJPanel.setBackground(new java.awt.Color(255, 255, 255));

        profAnalyticsTbl.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        profAnalyticsTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Professor Id", "Professor Name", "Courses Teaching", "Rating"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(profAnalyticsTbl);
        if (profAnalyticsTbl.getColumnModel().getColumnCount() > 0) {
            profAnalyticsTbl.getColumnModel().getColumn(0).setResizable(false);
            profAnalyticsTbl.getColumnModel().getColumn(0).setPreferredWidth(10);
            profAnalyticsTbl.getColumnModel().getColumn(1).setResizable(false);
            profAnalyticsTbl.getColumnModel().getColumn(2).setResizable(false);
            profAnalyticsTbl.getColumnModel().getColumn(3).setResizable(false);
            profAnalyticsTbl.getColumnModel().getColumn(3).setHeaderValue("Rating");
        }

        javax.swing.GroupLayout AdminProfessorJPanelLayout = new javax.swing.GroupLayout(AdminProfessorJPanel);
        AdminProfessorJPanel.setLayout(AdminProfessorJPanelLayout);
        AdminProfessorJPanelLayout.setHorizontalGroup(
            AdminProfessorJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminProfessorJPanelLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 839, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(195, Short.MAX_VALUE))
        );
        AdminProfessorJPanelLayout.setVerticalGroup(
            AdminProfessorJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminProfessorJPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        adminTabbedPane.addTab("Professor Analytics", AdminProfessorJPanel);

        AdminStudentJPanel.setBackground(new java.awt.Color(255, 255, 255));

        studentAnalyticsTbl.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        studentAnalyticsTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Student Id", "Student Name", "Courses Enrolled", "Average GPA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(studentAnalyticsTbl);
        if (studentAnalyticsTbl.getColumnModel().getColumnCount() > 0) {
            studentAnalyticsTbl.getColumnModel().getColumn(0).setResizable(false);
            studentAnalyticsTbl.getColumnModel().getColumn(0).setPreferredWidth(10);
            studentAnalyticsTbl.getColumnModel().getColumn(1).setResizable(false);
            studentAnalyticsTbl.getColumnModel().getColumn(2).setResizable(false);
            studentAnalyticsTbl.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout AdminStudentJPanelLayout = new javax.swing.GroupLayout(AdminStudentJPanel);
        AdminStudentJPanel.setLayout(AdminStudentJPanelLayout);
        AdminStudentJPanelLayout.setHorizontalGroup(
            AdminStudentJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminStudentJPanelLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 839, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(195, Short.MAX_VALUE))
        );
        AdminStudentJPanelLayout.setVerticalGroup(
            AdminStudentJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminStudentJPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        adminTabbedPane.addTab("Student Analytics", AdminStudentJPanel);

        AdminCoursesJPanel.setBackground(new java.awt.Color(255, 255, 255));

        courseAnalyticsTbl.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        courseAnalyticsTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Course Id", "Course Name", "Student Enrolled"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(courseAnalyticsTbl);
        if (courseAnalyticsTbl.getColumnModel().getColumnCount() > 0) {
            courseAnalyticsTbl.getColumnModel().getColumn(0).setResizable(false);
            courseAnalyticsTbl.getColumnModel().getColumn(0).setPreferredWidth(10);
            courseAnalyticsTbl.getColumnModel().getColumn(1).setResizable(false);
            courseAnalyticsTbl.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout AdminCoursesJPanelLayout = new javax.swing.GroupLayout(AdminCoursesJPanel);
        AdminCoursesJPanel.setLayout(AdminCoursesJPanelLayout);
        AdminCoursesJPanelLayout.setHorizontalGroup(
            AdminCoursesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminCoursesJPanelLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 839, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(195, Short.MAX_VALUE))
        );
        AdminCoursesJPanelLayout.setVerticalGroup(
            AdminCoursesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminCoursesJPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        adminTabbedPane.addTab("Course Catalog", AdminCoursesJPanel);

        javax.swing.GroupLayout adminPanelLayout = new javax.swing.GroupLayout(adminPanel);
        adminPanel.setLayout(adminPanelLayout);
        adminPanelLayout.setHorizontalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(adminTabbedPane)
                .addGap(3, 3, 3))
        );
        adminPanelLayout.setVerticalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adminTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(adminPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        HomeJPanel.remove(this);
        CardLayout layout = (CardLayout) HomeJPanel.getLayout();
        layout.previous(HomeJPanel);
    }//GEN-LAST:event_logoutBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminCoursesJPanel;
    private javax.swing.JPanel AdminHomeJPanel;
    private javax.swing.JPanel AdminProfessorJPanel;
    private javax.swing.JPanel AdminStudentJPanel;
    private javax.swing.JPanel adminLogoPanel;
    private javax.swing.JPanel adminPanel;
    private javax.swing.JLabel adminPanelLabel;
    private javax.swing.JTabbedPane adminTabbedPane;
    private javax.swing.JTable courseAnalyticsTbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JTable profAnalyticsTbl;
    private javax.swing.JTable studentAnalyticsTbl;
    private javax.swing.JLabel studentHomeLabel;
    // End of variables declaration//GEN-END:variables

    private void populateProfessorAnalytics() {
        DefaultTableModel dtm = (DefaultTableModel) profAnalyticsTbl.getModel();
        dtm.setRowCount(0);
        ArrayList <String> values = manageprofessor.fetchProfessorAnalytics();
        Object[] row = new Object[4];
        for (String record : values) {
            String[] recordValues = record.split(",");
            row[0]= recordValues[0];
            row[1] = recordValues[1];
            row[2] = recordValues[2];
            row[3] = recordValues[3];
            dtm.addRow(row);
        }
        }
    
    
    private void populateStudentAnalytics() {
        DefaultTableModel dtm = (DefaultTableModel) studentAnalyticsTbl.getModel();
        dtm.setRowCount(0);
ArrayList <String> values = managestudent.fetchStudentAnalytics();
        Object[] row = new Object[4];
        for (String record : values) {
            String[] recordValues = record.split(",");
            row[0]= recordValues[0];
            row[1] = recordValues[1];
            row[2] = recordValues[2];
            row[3] = recordValues[3];
            dtm.addRow(row);
        }
    }
    private void populateCourseAnalytics() {
        DefaultTableModel dtm = (DefaultTableModel) courseAnalyticsTbl.getModel();
        dtm.setRowCount(0);
ArrayList <String> values = managecourse.fetchCourseAnalytics();
        Object[] row = new Object[3];
        for (String record : values) {
            String[] recordValues = record.split(",");
            row[0]= recordValues[0];
            row[1] = recordValues[1];
            row[2] = recordValues[2];
            dtm.addRow(row);
        }
    }
}
