/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.LoginFramework;

import Business.Student.CourseRegistered;
import Business.Student.Student;
import Business.Student.StudentDirectory;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author dwive
 */
public class StudentSignupJPanel extends javax.swing.JPanel {

    /**
     * Creates new form StudentSignupJPanel
     */
    private JPanel homeJPanel;
    private int nextUserId;
    private StudentDirectory managestudent;
    
    StudentSignupJPanel(JPanel homeJPanel, int nextUserId, StudentDirectory managestudent) {
        initComponents();
        this.homeJPanel = homeJPanel;
        this.nextUserId=nextUserId;
        this.managestudent = managestudent;
        Sidtxt.setText(String.valueOf(nextUserId));
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ssignuplbl = new javax.swing.JLabel();
        idlbl = new javax.swing.JLabel();
        Sidtxt = new javax.swing.JTextField();
        fullnamelbl = new javax.swing.JLabel();
        Sfullnametxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Sagetxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Screatepwd = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        Sconfirmpwd = new javax.swing.JPasswordField();
        Saccountbtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Semailtxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Scontacttxt = new javax.swing.JTextField();
        Sregiontxt = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        Ssignuplbl.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        Ssignuplbl.setForeground(new java.awt.Color(102, 51, 0));
        Ssignuplbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ssignuplbl.setText("STUDENT SIGN UP ");

        idlbl.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        idlbl.setForeground(new java.awt.Color(102, 51, 0));
        idlbl.setText("ID:");

        Sidtxt.setEditable(false);
        Sidtxt.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N

        fullnamelbl.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        fullnamelbl.setForeground(new java.awt.Color(102, 51, 0));
        fullnamelbl.setText("Full Name:");

        Sfullnametxt.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 51, 0));
        jLabel4.setText("Age:");

        Sagetxt.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 51, 0));
        jLabel5.setText("Region:");

        jLabel12.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 51, 0));
        jLabel12.setText("Create Password:");

        Screatepwd.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        Screatepwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScreatepwdActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 51, 0));
        jLabel13.setText("Confirm Password:");

        Sconfirmpwd.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N

        Saccountbtn.setBackground(new java.awt.Color(102, 51, 0));
        Saccountbtn.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        Saccountbtn.setForeground(new java.awt.Color(255, 255, 255));
        Saccountbtn.setText(" CREATE ACCOUNT");
        Saccountbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaccountbtnActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 51, 0));
        jLabel6.setText("Email Address:");

        Semailtxt.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 51, 0));
        jLabel7.setText("Contact Number:");

        Scontacttxt.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        Scontacttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScontacttxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(idlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                .addComponent(Sidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fullnamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Sfullnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Screatepwd, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                                    .addComponent(Sconfirmpwd))))
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                        .addGap(18, 38, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Sagetxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Scontacttxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Semailtxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Sregiontxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Saccountbtn)
                        .addGap(276, 276, 276)))
                .addGap(225, 225, 225))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Ssignuplbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(Ssignuplbl, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Semailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fullnamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Scontacttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sfullnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sregiontxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Screatepwd, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sconfirmpwd, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sagetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(101, 101, 101)
                .addComponent(Saccountbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SaccountbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaccountbtnActionPerformed
        // Create  professor
        int studentId = Integer.parseInt(Sidtxt.getText());
        String studentName = Sfullnametxt.getText();
        int studentAge = Integer.parseInt(Sagetxt.getText());
        String studentRegion = Sregiontxt.getText();
        char[] studentPassword = Screatepwd.getPassword();
        char[] confirmPassword = Sconfirmpwd.getPassword();
        String studentEmail = Semailtxt.getText();
        long studentPhone = Long.parseLong(Scontacttxt.getText());
        ArrayList<CourseRegistered> coursesRegisteredList = new ArrayList<>();
        ArrayList<CourseRegistered> transcript = new ArrayList<>();
        
        Boolean passwordVerification = passwordVerify(studentPassword, confirmPassword);
        if(passwordVerification){
            JOptionPane.showMessageDialog(null, "Student account created successfully. Your User ID is: "+ studentId +".");
            Student student = managestudent.addStudent(coursesRegisteredList, transcript, false, false, studentId, studentName, studentPassword, studentAge, studentRegion, studentPhone, studentEmail, "Student");
        }
        
    }//GEN-LAST:event_SaccountbtnActionPerformed

    private void ScontacttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScontacttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ScontacttxtActionPerformed

    private void ScreatepwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScreatepwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ScreatepwdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Saccountbtn;
    private javax.swing.JTextField Sagetxt;
    private javax.swing.JPasswordField Sconfirmpwd;
    private javax.swing.JTextField Scontacttxt;
    private javax.swing.JPasswordField Screatepwd;
    private javax.swing.JTextField Semailtxt;
    private javax.swing.JTextField Sfullnametxt;
    private javax.swing.JTextField Sidtxt;
    private javax.swing.JTextField Sregiontxt;
    private javax.swing.JLabel Ssignuplbl;
    private javax.swing.JLabel fullnamelbl;
    private javax.swing.JLabel idlbl;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables

    private Boolean passwordVerify(char[] newPassword, char[] confirmPassword) {
        Boolean flag = true;
        String password = new String(newPassword);
        if(((password.matches("[a-zA-Z0-9@._-]{3,}") == false))){
            JOptionPane.showMessageDialog(null, "Incorrect Password Format");
            flag = false;
        }
        String confirmpassword = new String(confirmPassword);
        if(password.equals(confirmpassword)==false){
            JOptionPane.showMessageDialog(null, "Confirm password doesnot match with set Password");
            flag = false;
        }
        return flag;        
    }
}
