/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole;

import Business.Course.Course;
import Business.Course.CourseDirectory;
import Business.Faculty.Professor;
import Business.Faculty.ProfessorDirectory;
import Business.Faculty.StudentGradeRequest;
import Business.Faculty.StudentGradeRequestDirectory;
import Business.Person.PersonDirectory;
import Business.Student.StudentDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raisi
 */
public class ProfessorJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProfessorJPanel
     */
    private JPanel HomeJPanel;
    Professor professor;
    private ProfessorDirectory manageprofessor;
    private PersonDirectory manageperson;
    private CourseDirectory managecourse;
    private StudentDirectory managestudent;
    private StudentGradeRequestDirectory managegrades;
    
    public ProfessorJPanel(JPanel HomeJPanel, ProfessorDirectory manageprofessor, CourseDirectory managecourse, StudentDirectory managestudent, PersonDirectory manageperson, StudentGradeRequestDirectory managegrades) {
        initComponents();
        this.HomeJPanel = HomeJPanel;
        this.manageprofessor = manageprofessor;
        this.managecourse = managecourse;
        this.manageperson = manageperson;
        this.managegrades = managegrades;
        findProfessor();
        viewProfessorDetails();
        populateCourses();
        populatesStudentRequest();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        professorPanelLabel = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JButton();
        professortabbedpane = new javax.swing.JTabbedPane();
        professorHomeJPanel = new javax.swing.JPanel();
        profHomeLabel = new javax.swing.JLabel();
        profHomeImage = new javax.swing.JLabel();
        professorProfileJPanel = new javax.swing.JPanel();
        updatedetailslbl = new javax.swing.JLabel();
        idlbl = new javax.swing.JLabel();
        idtxt = new javax.swing.JTextField();
        namelbl = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        agelbl = new javax.swing.JLabel();
        agetxt = new javax.swing.JTextField();
        regionlbl = new javax.swing.JLabel();
        regiontxt = new javax.swing.JTextField();
        phonebl = new javax.swing.JLabel();
        phonetxt = new javax.swing.JTextField();
        languagelbl = new javax.swing.JLabel();
        languagetxt = new javax.swing.JTextField();
        paperpublishlbl = new javax.swing.JLabel();
        paperpublishtxt = new javax.swing.JTextField();
        experiencelbl = new javax.swing.JLabel();
        experiencetxt = new javax.swing.JTextField();
        updatedetailsbtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        updatepasswordlbl = new javax.swing.JLabel();
        prevpasslbl = new javax.swing.JLabel();
        prevpasstxt = new javax.swing.JPasswordField();
        newpasslbl = new javax.swing.JLabel();
        newpasstxt = new javax.swing.JPasswordField();
        confirmpasslbl = new javax.swing.JLabel();
        confirmpasstxt = new javax.swing.JPasswordField();
        updatepassbtn = new javax.swing.JButton();
        emaillbl = new javax.swing.JLabel();
        emailtxt = new javax.swing.JTextField();
        professorManageCoursesJPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        managecoursetbl = new javax.swing.JTable();
        updatecoursebtn = new javax.swing.JButton();
        courseidlbl = new javax.swing.JLabel();
        courseidtxt = new javax.swing.JTextField();
        coursenamelbl = new javax.swing.JLabel();
        coursenametxt = new javax.swing.JTextField();
        semesterlbl = new javax.swing.JLabel();
        semestercombo = new javax.swing.JComboBox<>();
        classcapacitylbl = new javax.swing.JLabel();
        classcapacitytxt = new javax.swing.JTextField();
        savecoursebtn = new javax.swing.JButton();
        updatecourselbl = new javax.swing.JLabel();
        professorManageStudentsJPanel = new javax.swing.JPanel();
        managestudetlbl = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        studentrequesttbl = new javax.swing.JTable();
        managestudenttbl = new javax.swing.JButton();
        studentcourseidlbl = new javax.swing.JLabel();
        studentcourseidtxt = new javax.swing.JTextField();
        studentcoursenamelbl = new javax.swing.JLabel();
        studentcoursenametxt = new javax.swing.JTextField();
        studentidlbl = new javax.swing.JLabel();
        studentidtxt = new javax.swing.JTextField();
        studentnamelbl = new javax.swing.JLabel();
        studentnametxt = new javax.swing.JTextField();
        studentgradelbl = new javax.swing.JLabel();
        studentgradecombo = new javax.swing.JComboBox<>();
        submitstudentrequestbtn = new javax.swing.JButton();
        professorAddCourseJPanel = new javax.swing.JPanel();
        addcoursenamelbl = new javax.swing.JLabel();
        addcoursenametxt = new javax.swing.JTextField();
        addcoursesemesterlbl = new javax.swing.JLabel();
        addcoursesemestercombo = new javax.swing.JComboBox<>();
        addcourseclasscapacitylbl = new javax.swing.JLabel();
        addcourseclasscapacitytxt = new javax.swing.JTextField();
        addcoursebtn = new javax.swing.JButton();
        cclogoicon = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(102, 51, 0));
        setToolTipText("");
        setMaximumSize(new java.awt.Dimension(1200, 650));

        professorPanelLabel.setBackground(new java.awt.Color(255, 255, 255));
        professorPanelLabel.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        professorPanelLabel.setForeground(new java.awt.Color(102, 51, 0));
        professorPanelLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        professorPanelLabel.setText("PROFESSOR PANEL");

        logoutBtn.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(102, 51, 0));
        logoutBtn.setText("LOGOUT");
        logoutBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        logoutBtn.setContentAreaFilled(false);
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        professortabbedpane.setBackground(new java.awt.Color(255, 255, 255));
        professortabbedpane.setForeground(new java.awt.Color(102, 51, 0));
        professortabbedpane.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N

        professorHomeJPanel.setBackground(new java.awt.Color(255, 255, 255));
        professorHomeJPanel.setPreferredSize(new java.awt.Dimension(1200, 521));

        profHomeLabel.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        profHomeLabel.setForeground(new java.awt.Color(102, 51, 0));
        profHomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        profHomeLabel.setText("<html>Welcome to the Professor Panel! Your all-in-one solution for seamless course management, meaningful student engagement, efficient schedule coordination, <br>and personalized profile maintenance.  <br>Here, you'll find the tools and resources to elevate your teaching experience. Streamline your courses, connect with your students, and stay organized with ease.  <br>Let's embark on this educational journey together, making the most of every opportunity to inspire and educate.</html>");

        profHomeImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/professorHome.png"))); // NOI18N

        javax.swing.GroupLayout professorHomeJPanelLayout = new javax.swing.GroupLayout(professorHomeJPanel);
        professorHomeJPanel.setLayout(professorHomeJPanelLayout);
        professorHomeJPanelLayout.setHorizontalGroup(
            professorHomeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(professorHomeJPanelLayout.createSequentialGroup()
                .addGroup(professorHomeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(professorHomeJPanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(profHomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 1115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(professorHomeJPanelLayout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addComponent(profHomeImage, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        professorHomeJPanelLayout.setVerticalGroup(
            professorHomeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(professorHomeJPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(profHomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(profHomeImage, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        professortabbedpane.addTab("Home", professorHomeJPanel);

        professorProfileJPanel.setBackground(new java.awt.Color(255, 255, 255));
        professorProfileJPanel.setForeground(new java.awt.Color(102, 51, 0));

        updatedetailslbl.setFont(new java.awt.Font("Cambria Math", 1, 16)); // NOI18N
        updatedetailslbl.setForeground(new java.awt.Color(102, 51, 0));
        updatedetailslbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        updatedetailslbl.setText("Update Basic Details");

        idlbl.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        idlbl.setText("ID:");

        idtxt.setEditable(false);
        idtxt.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N

        namelbl.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        namelbl.setText("Full Name:");

        nametxt.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N

        agelbl.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        agelbl.setText("Age:");

        agetxt.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N

        regionlbl.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        regionlbl.setText("Region:");

        regiontxt.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N

        phonebl.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        phonebl.setText("Contact Number:");

        phonetxt.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N

        languagelbl.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        languagelbl.setText("<html>Language of <br>Instruction:</html>");

        languagetxt.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N

        paperpublishlbl.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        paperpublishlbl.setText("<html>Number of Research <br>Papers Published:</html>");

        paperpublishtxt.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        paperpublishtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paperpublishtxtActionPerformed(evt);
            }
        });

        experiencelbl.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        experiencelbl.setText("<html>Years Of<br>Experience:</html>");

        experiencetxt.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        experiencetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                experiencetxtActionPerformed(evt);
            }
        });

        updatedetailsbtn.setBackground(new java.awt.Color(102, 51, 0));
        updatedetailsbtn.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        updatedetailsbtn.setForeground(new java.awt.Color(255, 255, 255));
        updatedetailsbtn.setText("UPDATE DETAILS");
        updatedetailsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatedetailsbtnActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        updatepasswordlbl.setFont(new java.awt.Font("Cambria Math", 1, 16)); // NOI18N
        updatepasswordlbl.setForeground(new java.awt.Color(102, 51, 0));
        updatepasswordlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        updatepasswordlbl.setText("Update Password");

        prevpasslbl.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        prevpasslbl.setText("Previous Password:");

        prevpasstxt.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N

        newpasslbl.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        newpasslbl.setText("New Password:");

        newpasstxt.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N

        confirmpasslbl.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        confirmpasslbl.setText("Confirm Password:");

        confirmpasstxt.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N

        updatepassbtn.setBackground(new java.awt.Color(102, 51, 0));
        updatepassbtn.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        updatepassbtn.setForeground(new java.awt.Color(255, 255, 255));
        updatepassbtn.setText("UPDATE PASSWORD");
        updatepassbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatepassbtnActionPerformed(evt);
            }
        });

        emaillbl.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        emaillbl.setText("Email:");

        emailtxt.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N

        javax.swing.GroupLayout professorProfileJPanelLayout = new javax.swing.GroupLayout(professorProfileJPanel);
        professorProfileJPanel.setLayout(professorProfileJPanelLayout);
        professorProfileJPanelLayout.setHorizontalGroup(
            professorProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(professorProfileJPanelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(professorProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(professorProfileJPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(updatedetailslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(professorProfileJPanelLayout.createSequentialGroup()
                        .addGroup(professorProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(professorProfileJPanelLayout.createSequentialGroup()
                                .addGroup(professorProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(professorProfileJPanelLayout.createSequentialGroup()
                                        .addComponent(phonebl, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(phonetxt))
                                    .addGroup(professorProfileJPanelLayout.createSequentialGroup()
                                        .addComponent(regionlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(regiontxt))
                                    .addGroup(professorProfileJPanelLayout.createSequentialGroup()
                                        .addComponent(agelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(agetxt))
                                    .addGroup(professorProfileJPanelLayout.createSequentialGroup()
                                        .addComponent(namelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nametxt))
                                    .addGroup(professorProfileJPanelLayout.createSequentialGroup()
                                        .addComponent(idlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(idtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(professorProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(professorProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, professorProfileJPanelLayout.createSequentialGroup()
                                            .addGap(2, 2, 2)
                                            .addComponent(languagelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(professorProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(paperpublishlbl)
                                            .addComponent(experiencelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(emaillbl, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(updatedetailsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(professorProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(languagetxt)
                            .addComponent(paperpublishtxt)
                            .addComponent(experiencetxt)
                            .addComponent(emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(professorProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(professorProfileJPanelLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(updatepassbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(professorProfileJPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(professorProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(updatepasswordlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(professorProfileJPanelLayout.createSequentialGroup()
                                .addGroup(professorProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(prevpasslbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(newpasslbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(confirmpasslbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(professorProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(prevpasstxt)
                                    .addComponent(newpasstxt)
                                    .addComponent(confirmpasstxt, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(109, 109, 109))
        );
        professorProfileJPanelLayout.setVerticalGroup(
            professorProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(professorProfileJPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(professorProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(professorProfileJPanelLayout.createSequentialGroup()
                        .addGroup(professorProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(professorProfileJPanelLayout.createSequentialGroup()
                                .addComponent(updatedetailslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addGroup(professorProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(professorProfileJPanelLayout.createSequentialGroup()
                                        .addComponent(languagelbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(72, 72, 72)
                                        .addGroup(professorProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(experiencelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(experiencetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(professorProfileJPanelLayout.createSequentialGroup()
                                        .addGap(58, 58, 58)
                                        .addComponent(paperpublishlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(professorProfileJPanelLayout.createSequentialGroup()
                                        .addGroup(professorProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(professorProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(professorProfileJPanelLayout.createSequentialGroup()
                                                    .addComponent(languagetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(24, 24, 24)
                                                    .addComponent(paperpublishtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(125, 125, 125))
                                                .addGroup(professorProfileJPanelLayout.createSequentialGroup()
                                                    .addGroup(professorProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(professorProfileJPanelLayout.createSequentialGroup()
                                                            .addGap(117, 117, 117)
                                                            .addGroup(professorProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(agetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(agelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(professorProfileJPanelLayout.createSequentialGroup()
                                                            .addGroup(professorProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(idlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(idtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGap(29, 29, 29)
                                                            .addGroup(professorProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(namelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                    .addGap(32, 32, 32)
                                                    .addGroup(professorProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(regionlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(regiontxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(emaillbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(professorProfileJPanelLayout.createSequentialGroup()
                                                .addGap(178, 178, 178)
                                                .addComponent(emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(26, 26, 26)
                                        .addGroup(professorProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(phonebl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(phonetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(professorProfileJPanelLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(updatepasswordlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(professorProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(professorProfileJPanelLayout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(prevpasstxt))
                                    .addComponent(prevpasslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(professorProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(newpasslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(newpasstxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(professorProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(confirmpasslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(confirmpasstxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(professorProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(updatepassbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updatedetailsbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        professortabbedpane.addTab("Profile", professorProfileJPanel);

        professorManageCoursesJPanel.setBackground(new java.awt.Color(255, 255, 255));

        managecoursetbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Course ID", "Course Name", "Semester", "Class Capacity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(managecoursetbl);
        if (managecoursetbl.getColumnModel().getColumnCount() > 0) {
            managecoursetbl.getColumnModel().getColumn(0).setResizable(false);
            managecoursetbl.getColumnModel().getColumn(0).setPreferredWidth(10);
            managecoursetbl.getColumnModel().getColumn(1).setResizable(false);
            managecoursetbl.getColumnModel().getColumn(2).setResizable(false);
            managecoursetbl.getColumnModel().getColumn(3).setResizable(false);
            managecoursetbl.getColumnModel().getColumn(3).setPreferredWidth(10);
        }

        updatecoursebtn.setBackground(new java.awt.Color(102, 51, 0));
        updatecoursebtn.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        updatecoursebtn.setForeground(new java.awt.Color(255, 255, 255));
        updatecoursebtn.setText("Update");
        updatecoursebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatecoursebtnActionPerformed(evt);
            }
        });

        courseidlbl.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        courseidlbl.setText("Course ID:");

        courseidtxt.setEditable(false);
        courseidtxt.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        courseidtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseidtxtActionPerformed(evt);
            }
        });

        coursenamelbl.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        coursenamelbl.setText("Course Name:");

        coursenametxt.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        coursenametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coursenametxtActionPerformed(evt);
            }
        });

        semesterlbl.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        semesterlbl.setText("Semester:");

        semestercombo.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        semestercombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fall 2023", "Spring 2024", "Summer 2024", "Fall 2024", "Spring 2025", "Summer 2025", "Fall 2025", "Spring 2026", "Summer 2026" }));

        classcapacitylbl.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        classcapacitylbl.setText("Class Capacity:");

        classcapacitytxt.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        classcapacitytxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classcapacitytxtActionPerformed(evt);
            }
        });

        savecoursebtn.setBackground(new java.awt.Color(102, 51, 0));
        savecoursebtn.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        savecoursebtn.setForeground(new java.awt.Color(255, 255, 255));
        savecoursebtn.setText("Save");
        savecoursebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savecoursebtnActionPerformed(evt);
            }
        });

        updatecourselbl.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        updatecourselbl.setForeground(new java.awt.Color(102, 51, 0));
        updatecourselbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        updatecourselbl.setText("Update Course Details");

        javax.swing.GroupLayout professorManageCoursesJPanelLayout = new javax.swing.GroupLayout(professorManageCoursesJPanel);
        professorManageCoursesJPanel.setLayout(professorManageCoursesJPanelLayout);
        professorManageCoursesJPanelLayout.setHorizontalGroup(
            professorManageCoursesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(professorManageCoursesJPanelLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(professorManageCoursesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updatecoursebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(professorManageCoursesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(professorManageCoursesJPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addGroup(professorManageCoursesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(professorManageCoursesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(professorManageCoursesJPanelLayout.createSequentialGroup()
                                    .addComponent(semesterlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(42, 42, 42)
                                    .addComponent(semestercombo, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(professorManageCoursesJPanelLayout.createSequentialGroup()
                                    .addComponent(classcapacitylbl, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(42, 42, 42)
                                    .addGroup(professorManageCoursesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(savecoursebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(classcapacitytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(professorManageCoursesJPanelLayout.createSequentialGroup()
                                .addComponent(courseidlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(courseidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(professorManageCoursesJPanelLayout.createSequentialGroup()
                                .addComponent(coursenamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(coursenametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(professorManageCoursesJPanelLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(updatecourselbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(70, 70, 70))
        );
        professorManageCoursesJPanelLayout.setVerticalGroup(
            professorManageCoursesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(professorManageCoursesJPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(professorManageCoursesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(professorManageCoursesJPanelLayout.createSequentialGroup()
                        .addComponent(updatecourselbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addGroup(professorManageCoursesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(courseidlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(courseidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(professorManageCoursesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(coursenamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(coursenametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(professorManageCoursesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(semesterlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(semestercombo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(professorManageCoursesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(classcapacitylbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(classcapacitytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29)
                .addGroup(professorManageCoursesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updatecoursebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(savecoursebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        professortabbedpane.addTab("Manage Courses", professorManageCoursesJPanel);

        professorManageStudentsJPanel.setBackground(new java.awt.Color(255, 255, 255));

        managestudetlbl.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        managestudetlbl.setForeground(new java.awt.Color(102, 51, 0));
        managestudetlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        managestudetlbl.setText("Manage Student Request");

        studentrequesttbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Course ID", "Course Name", "Student ID", "Student Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(studentrequesttbl);
        if (studentrequesttbl.getColumnModel().getColumnCount() > 0) {
            studentrequesttbl.getColumnModel().getColumn(0).setResizable(false);
            studentrequesttbl.getColumnModel().getColumn(0).setPreferredWidth(10);
            studentrequesttbl.getColumnModel().getColumn(1).setResizable(false);
            studentrequesttbl.getColumnModel().getColumn(2).setResizable(false);
            studentrequesttbl.getColumnModel().getColumn(2).setPreferredWidth(10);
            studentrequesttbl.getColumnModel().getColumn(3).setResizable(false);
        }

        managestudenttbl.setBackground(new java.awt.Color(102, 51, 0));
        managestudenttbl.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        managestudenttbl.setForeground(new java.awt.Color(255, 255, 255));
        managestudenttbl.setText("Manage ");
        managestudenttbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managestudenttblActionPerformed(evt);
            }
        });

        studentcourseidlbl.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        studentcourseidlbl.setText("Course ID:");

        studentcourseidtxt.setEditable(false);
        studentcourseidtxt.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        studentcourseidtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentcourseidtxtActionPerformed(evt);
            }
        });

        studentcoursenamelbl.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        studentcoursenamelbl.setText("Course Name:");

        studentcoursenametxt.setEditable(false);
        studentcoursenametxt.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        studentcoursenametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentcoursenametxtActionPerformed(evt);
            }
        });

        studentidlbl.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        studentidlbl.setText("Student ID:");

        studentidtxt.setEditable(false);
        studentidtxt.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        studentidtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentidtxtActionPerformed(evt);
            }
        });

        studentnamelbl.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        studentnamelbl.setText("Student  Name:");

        studentnametxt.setEditable(false);
        studentnametxt.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        studentnametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentnametxtActionPerformed(evt);
            }
        });

        studentgradelbl.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        studentgradelbl.setText("Grade:");

        studentgradecombo.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        studentgradecombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "F" }));

        submitstudentrequestbtn.setBackground(new java.awt.Color(102, 51, 0));
        submitstudentrequestbtn.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        submitstudentrequestbtn.setForeground(new java.awt.Color(255, 255, 255));
        submitstudentrequestbtn.setText("Submit");
        submitstudentrequestbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitstudentrequestbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout professorManageStudentsJPanelLayout = new javax.swing.GroupLayout(professorManageStudentsJPanel);
        professorManageStudentsJPanel.setLayout(professorManageStudentsJPanelLayout);
        professorManageStudentsJPanelLayout.setHorizontalGroup(
            professorManageStudentsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(professorManageStudentsJPanelLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(professorManageStudentsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(managestudenttbl, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(professorManageStudentsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(professorManageStudentsJPanelLayout.createSequentialGroup()
                        .addComponent(studentidlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(studentidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(professorManageStudentsJPanelLayout.createSequentialGroup()
                        .addComponent(studentnamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(studentnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(professorManageStudentsJPanelLayout.createSequentialGroup()
                        .addComponent(studentgradelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addGroup(professorManageStudentsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(submitstudentrequestbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studentgradecombo, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(managestudetlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(professorManageStudentsJPanelLayout.createSequentialGroup()
                        .addComponent(studentcoursenamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(studentcoursenametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(professorManageStudentsJPanelLayout.createSequentialGroup()
                        .addComponent(studentcourseidlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(studentcourseidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        professorManageStudentsJPanelLayout.setVerticalGroup(
            professorManageStudentsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(professorManageStudentsJPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(professorManageStudentsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(professorManageStudentsJPanelLayout.createSequentialGroup()
                        .addComponent(managestudetlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(professorManageStudentsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(studentcourseidlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studentcourseidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(professorManageStudentsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(studentcoursenamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studentcoursenametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(professorManageStudentsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(studentidlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studentidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(professorManageStudentsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(studentnamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studentnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(professorManageStudentsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(studentgradelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studentgradecombo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(46, 46, 46)
                .addGroup(professorManageStudentsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(managestudenttbl, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitstudentrequestbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        professortabbedpane.addTab("Student Requests", professorManageStudentsJPanel);

        professorAddCourseJPanel.setBackground(new java.awt.Color(255, 255, 255));
        professorAddCourseJPanel.setForeground(new java.awt.Color(102, 51, 0));

        addcoursenamelbl.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        addcoursenamelbl.setText("Course Name:");

        addcoursenametxt.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N

        addcoursesemesterlbl.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        addcoursesemesterlbl.setText("Semester:");

        addcoursesemestercombo.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        addcoursesemestercombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fall 2023", "Spring 2024", "Summer 2024", "Fall 2024", "Spring 2025", "Summer 2025", "Fall 2025", "Spring 2026", "Summer 2026" }));

        addcourseclasscapacitylbl.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        addcourseclasscapacitylbl.setText("Class Capacity:");

        addcourseclasscapacitytxt.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N

        addcoursebtn.setBackground(new java.awt.Color(102, 51, 0));
        addcoursebtn.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        addcoursebtn.setForeground(new java.awt.Color(255, 255, 255));
        addcoursebtn.setText("Submit");
        addcoursebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcoursebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout professorAddCourseJPanelLayout = new javax.swing.GroupLayout(professorAddCourseJPanel);
        professorAddCourseJPanel.setLayout(professorAddCourseJPanelLayout);
        professorAddCourseJPanelLayout.setHorizontalGroup(
            professorAddCourseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(professorAddCourseJPanelLayout.createSequentialGroup()
                .addGap(357, 357, 357)
                .addGroup(professorAddCourseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addcoursenametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(professorAddCourseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(addcoursenamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(professorAddCourseJPanelLayout.createSequentialGroup()
                            .addComponent(addcoursesemesterlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(addcoursesemestercombo, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(professorAddCourseJPanelLayout.createSequentialGroup()
                            .addComponent(addcourseclasscapacitylbl, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(professorAddCourseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(addcourseclasscapacitytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(addcoursebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(421, Short.MAX_VALUE))
        );
        professorAddCourseJPanelLayout.setVerticalGroup(
            professorAddCourseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(professorAddCourseJPanelLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(professorAddCourseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addcoursenamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addcoursenametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(professorAddCourseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addcoursesemesterlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addcoursesemestercombo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(professorAddCourseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addcourseclasscapacitylbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addcourseclasscapacitytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(addcoursebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(211, Short.MAX_VALUE))
        );

        professortabbedpane.addTab("Add Course", professorAddCourseJPanel);

        cclogoicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cloud-campus small logo 1.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(cclogoicon, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(professorPanelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(professortabbedpane, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(professorPanelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cclogoicon, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(professortabbedpane))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        HomeJPanel.remove(this);
        CardLayout layout = (CardLayout) HomeJPanel.getLayout();
        layout.previous(HomeJPanel);
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void experiencetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_experiencetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_experiencetxtActionPerformed

    private void paperpublishtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paperpublishtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paperpublishtxtActionPerformed

    private void coursenametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coursenametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coursenametxtActionPerformed

    private void courseidtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseidtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseidtxtActionPerformed

    private void classcapacitytxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classcapacitytxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_classcapacitytxtActionPerformed

    private void studentidtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentidtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentidtxtActionPerformed

    private void studentnametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentnametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentnametxtActionPerformed

    private void studentcourseidtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentcourseidtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentcourseidtxtActionPerformed

    private void updatecoursebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatecoursebtnActionPerformed
        int selectedRowIndex = managecoursetbl.getSelectedRow();
        
        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select a row to view.");
        }
        else{
            DefaultTableModel model = (DefaultTableModel) managecoursetbl.getModel();
            Course selectedCourse = (Course) model.getValueAt(selectedRowIndex, 0);
            courseidtxt.setText(String.valueOf(selectedCourse.getCourseId()));
            coursenametxt.setText(selectedCourse.getCourseName());
            semestercombo.setSelectedItem(selectedCourse.getSemester());
            classcapacitytxt.setText(String.valueOf(selectedCourse.getClassCapacity()));
        }
    }//GEN-LAST:event_updatecoursebtnActionPerformed

    private void updatedetailsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatedetailsbtnActionPerformed
        Boolean flag = true;
        int personId = Integer.parseInt(idtxt.getText());
        String name = nametxt.getText();
        if(name.matches("[a-zA-Z ]+") == false){
            JOptionPane.showMessageDialog(null, "Incorrect Name");
            flag = false;
            nametxt.setText("");
        }
        String email = emailtxt.getText();
        if(email.matches("[a-zA-Z0-9.@]+[gmail|northeastern][.com|.edu]+") == false){
            JOptionPane.showMessageDialog(null, "Incorrect Email");
            flag = false;
            emailtxt.setText("");
        }
        int age = Integer.parseInt(agetxt.getText());
        if(age < 0 && age > 100){
            JOptionPane.showMessageDialog(null, "Incorrect Age");
            flag = false;
            agetxt.setText("");
        }
        String region = regiontxt.getText();
        if(region.matches("[a-zA-Z, ]+") == false){
            JOptionPane.showMessageDialog(null, "Incorrect Address");
            flag = false;
            regiontxt.setText("");
        }
        
        String phno = phonetxt.getText();
        if(phno.matches("[0-9]{10}") == false){
            JOptionPane.showMessageDialog(null, "Incorrect PhoneNumber");
            flag = false;
            phonetxt.setText("");
        }
        String language = languagetxt.getText();
        int researchPaper = Integer.parseInt(paperpublishtxt.getText());
        int experience = Integer.parseInt(experiencetxt.getText());
        
        Boolean updatePersonStatus = manageperson.updatePerson(personId, name, age, region, Long.parseLong(phno), email);
        Boolean updateProfStatus = manageprofessor.updateProfessor(personId, language, researchPaper, experience);
        if(flag==true && updatePersonStatus==true && updateProfStatus==true){
            professor.setName(name);
            professor.setAge(age);
            professor.setRegion(region);
            professor.setPhone(Long.parseLong(phno));
            professor.setEmail(email);
            professor.setLangOfInstruction(language);
            professor.setResearchPaperPublished(researchPaper);
            professor.setYearsOfExperience(experience);
            JOptionPane.showMessageDialog(null, "Professor details updated successfully!");     
        }
        else{
            JOptionPane.showMessageDialog(null, "Error while updating Professor details. Check the information before submitting!");
        }

    }//GEN-LAST:event_updatedetailsbtnActionPerformed

    private void updatepassbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatepassbtnActionPerformed
        Boolean flag = true;
        int personId = Integer.parseInt(idtxt.getText());
        String prevPassword =new String(prevpasstxt.getPassword());
        String password = new String(newpasstxt.getPassword());
        String confirmpassword = new String(confirmpasstxt.getPassword());
        if(prevPassword.equals(password)){
            JOptionPane.showMessageDialog(null, "Previous password and new password cannot be same!");
            newpasstxt.setText("");
            confirmpasstxt.setText("");
            flag = false;
        }
        if(password.matches("[a-zA-Z0-9@._-]{3,}") == false){
            JOptionPane.showMessageDialog(null, "Incorrect Password Format");
            newpasstxt.setText("");
            confirmpasstxt.setText("");
            flag = false;
        }
        
        if(!password.equals(confirmpassword)){
            JOptionPane.showMessageDialog(null, "Confirm password doesnot match with set Password");
            confirmpasstxt.setText("");
            flag = false;
        }
        Boolean checkExistingPassStatus = manageperson.checkExistingPass(personId, prevPassword);
        if(checkExistingPassStatus==false){
            JOptionPane.showMessageDialog(null, "Incorrect Previous Password!");
            prevpasstxt.setText("");
            flag = false;
        }
//        System.out.println(prevPassword +"--"+password+"--"+confirmpassword);
        if(flag == true){
            Boolean updatePassStatus = manageperson.updatePassword(personId, password);
            if(updatePassStatus){
                JOptionPane.showMessageDialog(null, "Password updated Successfully");     
            }
            else{
                JOptionPane.showMessageDialog(null, "Error encountered while updating password. Try again!");     
            }   
        }
        else{
            JOptionPane.showMessageDialog(null, "Re-enter correct details to update password.");
        }
    }//GEN-LAST:event_updatepassbtnActionPerformed

    private void addcoursebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcoursebtnActionPerformed
        int loggedProfId = manageprofessor.getLoggedProfessorID();
        String courseName = addcoursenametxt.getText();
        String semester = (String) addcoursesemestercombo.getSelectedItem();
        int classCapacity = Integer.parseInt(addcourseclasscapacitytxt.getText()); 
        
        Boolean addCourseStatus = manageprofessor.addCourse(loggedProfId, courseName, semester, classCapacity);
        if(addCourseStatus){
            populateCourses();
            addcoursenametxt.setText("");
            addcourseclasscapacitytxt.setText("");
            JOptionPane.showMessageDialog(null, "Course added successfully.");
        }
        else{
            JOptionPane.showMessageDialog(null, "Error encountered while adding course. Contact Admin team.");
        }
    }//GEN-LAST:event_addcoursebtnActionPerformed

    private void savecoursebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savecoursebtnActionPerformed
        int courseId = Integer.parseInt(courseidtxt.getText());
        String courseName = coursenametxt.getText();
        String semester = (String) semestercombo.getSelectedItem();
        int classCapacity = Integer.parseInt(classcapacitytxt.getText());
        
        Boolean updateCourseStatus = manageprofessor.updateCourse(courseId, courseName, semester, classCapacity);
        if(updateCourseStatus){
            populateCourses();
            courseidtxt.setText("");
            coursenametxt.setText("");
            classcapacitytxt.setText("");
            JOptionPane.showMessageDialog(null, "Course updated successfully.");
        }
        else{
            JOptionPane.showMessageDialog(null, "Error encountered while updating course. Contact Admin team.");
        }
    }//GEN-LAST:event_savecoursebtnActionPerformed

    private void managestudenttblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managestudenttblActionPerformed
        int selectedRowIndex = studentrequesttbl.getSelectedRow();
        
        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select a row to manage grade.");
        }
        else{
            DefaultTableModel model = (DefaultTableModel) studentrequesttbl.getModel();
            StudentGradeRequest gradeRequests = (StudentGradeRequest) model.getValueAt(selectedRowIndex, 0);
            studentcourseidtxt.setText(String.valueOf(gradeRequests.getRegisteredCourseId()));
            studentcoursenametxt.setText(gradeRequests.getRegisteredCourseName());
            studentidtxt.setText(String.valueOf(gradeRequests.getRegisteredStudentId()));
            studentnametxt.setText(String.valueOf(gradeRequests.getRegisteredStudentName()));
        }
    }//GEN-LAST:event_managestudenttblActionPerformed

    private void studentcoursenametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentcoursenametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentcoursenametxtActionPerformed

    private void submitstudentrequestbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitstudentrequestbtnActionPerformed
        int courseId = Integer.parseInt(studentcourseidtxt.getText());
        int studentId = Integer.parseInt(studentidtxt.getText());
        String grade = (String) studentgradecombo.getSelectedItem();
        if(grade!="None"){
            float gradeToPoint = getGradePoint(grade);
    //        int dialogResult = JOptionPane.showConfirmDialog(null, "Would you like to grade "+grade+" to Student "+studentId+" ?", "Warning", dialogBtn);
            Boolean updateGradeStatus = managegrades.updateGrade(courseId, studentId, gradeToPoint);
            if(updateGradeStatus){
                populatesStudentRequest();
                studentcourseidtxt.setText("");
                studentcoursenametxt.setText("");
                studentidtxt.setText("");
                studentnametxt.setText("");
                studentgradecombo.setSelectedIndex(0);
                JOptionPane.showMessageDialog(null, "Student graded successfully.");
            }
            else{
                JOptionPane.showMessageDialog(null, "Error encountered updating grade. Contact Admin team.");
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Please select a grade from options.");
        }
        
    }//GEN-LAST:event_submitstudentrequestbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addcoursebtn;
    private javax.swing.JLabel addcourseclasscapacitylbl;
    private javax.swing.JTextField addcourseclasscapacitytxt;
    private javax.swing.JLabel addcoursenamelbl;
    private javax.swing.JTextField addcoursenametxt;
    private javax.swing.JComboBox<String> addcoursesemestercombo;
    private javax.swing.JLabel addcoursesemesterlbl;
    private javax.swing.JLabel agelbl;
    private javax.swing.JTextField agetxt;
    private javax.swing.JLabel cclogoicon;
    private javax.swing.JLabel classcapacitylbl;
    private javax.swing.JTextField classcapacitytxt;
    private javax.swing.JLabel confirmpasslbl;
    private javax.swing.JPasswordField confirmpasstxt;
    private javax.swing.JLabel courseidlbl;
    private javax.swing.JTextField courseidtxt;
    private javax.swing.JLabel coursenamelbl;
    private javax.swing.JTextField coursenametxt;
    private javax.swing.JLabel emaillbl;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JLabel experiencelbl;
    private javax.swing.JTextField experiencetxt;
    private javax.swing.JLabel idlbl;
    private javax.swing.JTextField idtxt;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel languagelbl;
    private javax.swing.JTextField languagetxt;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JTable managecoursetbl;
    private javax.swing.JButton managestudenttbl;
    private javax.swing.JLabel managestudetlbl;
    private javax.swing.JLabel namelbl;
    private javax.swing.JTextField nametxt;
    private javax.swing.JLabel newpasslbl;
    private javax.swing.JPasswordField newpasstxt;
    private javax.swing.JLabel paperpublishlbl;
    private javax.swing.JTextField paperpublishtxt;
    private javax.swing.JLabel phonebl;
    private javax.swing.JTextField phonetxt;
    private javax.swing.JLabel prevpasslbl;
    private javax.swing.JPasswordField prevpasstxt;
    private javax.swing.JLabel profHomeImage;
    private javax.swing.JLabel profHomeLabel;
    private javax.swing.JPanel professorAddCourseJPanel;
    private javax.swing.JPanel professorHomeJPanel;
    private javax.swing.JPanel professorManageCoursesJPanel;
    private javax.swing.JPanel professorManageStudentsJPanel;
    private javax.swing.JLabel professorPanelLabel;
    private javax.swing.JPanel professorProfileJPanel;
    private javax.swing.JTabbedPane professortabbedpane;
    private javax.swing.JLabel regionlbl;
    private javax.swing.JTextField regiontxt;
    private javax.swing.JButton savecoursebtn;
    private javax.swing.JComboBox<String> semestercombo;
    private javax.swing.JLabel semesterlbl;
    private javax.swing.JLabel studentcourseidlbl;
    private javax.swing.JTextField studentcourseidtxt;
    private javax.swing.JLabel studentcoursenamelbl;
    private javax.swing.JTextField studentcoursenametxt;
    private javax.swing.JComboBox<String> studentgradecombo;
    private javax.swing.JLabel studentgradelbl;
    private javax.swing.JLabel studentidlbl;
    private javax.swing.JTextField studentidtxt;
    private javax.swing.JLabel studentnamelbl;
    private javax.swing.JTextField studentnametxt;
    private javax.swing.JTable studentrequesttbl;
    private javax.swing.JButton submitstudentrequestbtn;
    private javax.swing.JButton updatecoursebtn;
    private javax.swing.JLabel updatecourselbl;
    private javax.swing.JButton updatedetailsbtn;
    private javax.swing.JLabel updatedetailslbl;
    private javax.swing.JButton updatepassbtn;
    private javax.swing.JLabel updatepasswordlbl;
    // End of variables declaration//GEN-END:variables

    private void findProfessor(){
        int id = manageprofessor.getLoggedProfessorID();
        professor = manageprofessor.getProfessorByProfessorId(id);
    }
    
    private void viewProfessorDetails() {
        idtxt.setText(String.valueOf(professor.getPersonId()));
        nametxt.setText(professor.getName());
        agetxt.setText(String.valueOf(professor.getAge()));
        regiontxt.setText(professor.getRegion());
        phonetxt.setText(String.valueOf(professor.getPhone()));
        languagetxt.setText(professor.getLangOfInstruction());
        paperpublishtxt.setText(String.valueOf(professor.getResearchPaperPublished()));
        experiencetxt.setText(String.valueOf(professor.getYearsOfExperience()));
        emailtxt.setText(professor.getEmail());
    }

    private void populateCourses() {
        DefaultTableModel dtm = (DefaultTableModel) managecoursetbl.getModel();
        int activeProfessorId = manageprofessor.getLoggedProfessorID();
        dtm.setRowCount(0);
        for(Course course: managecourse.getCourseListByProfessor(activeProfessorId)){
            Object[] row = new Object[4];
            row[0] = course;
            row[1] = course.getCourseName();
            row[2] = course.getSemester();
            row[3] = course.getClassCapacity();
            dtm.addRow(row);      
        }
    }

    private void populatesStudentRequest() {
        DefaultTableModel dtm = (DefaultTableModel) studentrequesttbl.getModel();
        int activeProfessorId = manageprofessor.getLoggedProfessorID();
        dtm.setRowCount(0);
        if(managegrades.getStudentRequest(activeProfessorId)!=null){
            for(StudentGradeRequest gradeRequests: managegrades.getStudentRequest(activeProfessorId)){
                Object[] row = new Object[4];
//                System.out.println(gradeRequests.getRegisteredCourseName());
                row[0] = gradeRequests;
                row[1] = gradeRequests.getRegisteredCourseName();
                row[2] = gradeRequests.getRegisteredStudentId();
                row[3] = gradeRequests.getRegisteredStudentName();
                dtm.addRow(row);      
            }
        }
    } 

    private float getGradePoint(String grade) {
        float gradeToPoint = 0;
        switch (grade) {
            case "A+":
            case "A":
                gradeToPoint = (float) 4.0;
                break;
            case "A-":
                gradeToPoint = (float) 3.7;
                break;
            case "B+":
                gradeToPoint = (float) 3.3;
                break;
            case "B":
                gradeToPoint = (float) 3.0;
                break;
            case "B-":
                gradeToPoint = (float) 2.7;
                break;
            case "C+":
                gradeToPoint = (float) 2.3;
                break;
            case "C":
                gradeToPoint = (float) 2.0;
                break;
            case "C-":
                gradeToPoint = (float) 1.7;
                break;
            case "F":
                gradeToPoint = (float) 0.1;
                break;
        }
        return gradeToPoint;
    }
    
}
