/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.UniversalCertificationAuthority;

import Business.Database.SQLiteDatabaseConnection;
import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Anusha
 */
public class CertificationAuthorityJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CertificationAuthorityJPane
     */
    private JPanel homeJPanel;
    Connection conn;
    public CertificationAuthorityJPanel(JPanel homeJPanel) {
        initComponents();
        this.homeJPanel = homeJPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        CertificationLogoPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JButton();
        ThirdPartyLabel = new javax.swing.JLabel();
        CertificationPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        CertificationTabbedPane = new javax.swing.JTabbedPane();
        CertificationHomePanel = new javax.swing.JPanel();
        studentHomeLabel = new javax.swing.JLabel();
        ProvideCertificationPanel = new javax.swing.JPanel();
        text2 = new javax.swing.JLabel();
        comboStudent = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCertificateCourseDisplay = new javax.swing.JTable();
        btnAuthorize = new javax.swing.JButton();
        btnAuthorize1 = new javax.swing.JButton();

        jSplitPane1.setDividerLocation(130);
        jSplitPane1.setDividerSize(1);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        CertificationLogoPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cloud-campus small logo 1.png"))); // NOI18N
        jLabel1.setText("LOGO");

        logoutBtn.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(102, 51, 0));
        logoutBtn.setText("LOGOUT");
        logoutBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        logoutBtn.setContentAreaFilled(false);
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        ThirdPartyLabel.setBackground(new java.awt.Color(255, 255, 255));
        ThirdPartyLabel.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        ThirdPartyLabel.setForeground(new java.awt.Color(102, 51, 0));
        ThirdPartyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ThirdPartyLabel.setText("UNIVERSAL CERTIFICATION AUTHORITY LOGIN");

        javax.swing.GroupLayout CertificationLogoPanelLayout = new javax.swing.GroupLayout(CertificationLogoPanel);
        CertificationLogoPanel.setLayout(CertificationLogoPanelLayout);
        CertificationLogoPanelLayout.setHorizontalGroup(
            CertificationLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CertificationLogoPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(ThirdPartyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );
        CertificationLogoPanelLayout.setVerticalGroup(
            CertificationLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CertificationLogoPanelLayout.createSequentialGroup()
                .addGroup(CertificationLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CertificationLogoPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(CertificationLogoPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(CertificationLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ThirdPartyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 46, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jSplitPane1.setTopComponent(CertificationLogoPanel);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        CertificationTabbedPane.setBackground(new java.awt.Color(255, 255, 255));
        CertificationTabbedPane.setForeground(new java.awt.Color(102, 51, 0));
        CertificationTabbedPane.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N

        CertificationHomePanel.setBackground(new java.awt.Color(255, 255, 255));

        studentHomeLabel.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        studentHomeLabel.setForeground(new java.awt.Color(102, 51, 0));
        studentHomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        studentHomeLabel.setText("<html>Welcome to the Third-Party Portal!, your all-in-one solution for managing declaration requests from students who are seeking graduation approval. <br>Here, you'll find the tools and resources to efficiently review and approve graduation declaration requests from students. <br>Let's collaborate to ensure students get the recognition they deserve upon their successful completion of their academic journey.</html>");

        javax.swing.GroupLayout CertificationHomePanelLayout = new javax.swing.GroupLayout(CertificationHomePanel);
        CertificationHomePanel.setLayout(CertificationHomePanelLayout);
        CertificationHomePanelLayout.setHorizontalGroup(
            CertificationHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CertificationHomePanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(studentHomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 1115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        CertificationHomePanelLayout.setVerticalGroup(
            CertificationHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CertificationHomePanelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(studentHomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(335, Short.MAX_VALUE))
        );

        CertificationTabbedPane.addTab("Home", CertificationHomePanel);

        ProvideCertificationPanel.setBackground(new java.awt.Color(255, 255, 255));
        ProvideCertificationPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                ProvideCertificationPanelComponentShown(evt);
            }
        });

        text2.setText("<html>Please select a student from the drop down to chek grade and authorise the Certification</html>");

        comboStudent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None" }));

        tblCertificateCourseDisplay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Course Id", "Course Name", "Grade Received"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCertificateCourseDisplay);

        btnAuthorize.setBackground(new java.awt.Color(102, 51, 0));
        btnAuthorize.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        btnAuthorize.setForeground(new java.awt.Color(255, 255, 255));
        btnAuthorize.setText("AUTHORIZE CERTIFICATE");
        btnAuthorize.setEnabled(false);
        btnAuthorize.setOpaque(true);
        btnAuthorize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAuthorizeActionPerformed(evt);
            }
        });

        btnAuthorize1.setBackground(new java.awt.Color(102, 51, 0));
        btnAuthorize1.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        btnAuthorize1.setForeground(new java.awt.Color(255, 255, 255));
        btnAuthorize1.setText("SEARCH");
        btnAuthorize1.setOpaque(true);
        btnAuthorize1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAuthorize1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ProvideCertificationPanelLayout = new javax.swing.GroupLayout(ProvideCertificationPanel);
        ProvideCertificationPanel.setLayout(ProvideCertificationPanelLayout);
        ProvideCertificationPanelLayout.setHorizontalGroup(
            ProvideCertificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProvideCertificationPanelLayout.createSequentialGroup()
                .addGroup(ProvideCertificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProvideCertificationPanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(text2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(comboStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(btnAuthorize1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProvideCertificationPanelLayout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProvideCertificationPanelLayout.createSequentialGroup()
                        .addGap(486, 486, 486)
                        .addComponent(btnAuthorize, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        ProvideCertificationPanelLayout.setVerticalGroup(
            ProvideCertificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProvideCertificationPanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(ProvideCertificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAuthorize1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnAuthorize, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        CertificationTabbedPane.addTab("Provide Certification", ProvideCertificationPanel);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CertificationTabbedPane))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(CertificationTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout CertificationPanelLayout = new javax.swing.GroupLayout(CertificationPanel);
        CertificationPanel.setLayout(CertificationPanelLayout);
        CertificationPanelLayout.setHorizontalGroup(
            CertificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        CertificationPanelLayout.setVerticalGroup(
            CertificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CertificationPanelLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(CertificationPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        homeJPanel.remove(this);
        CardLayout layout = (CardLayout) homeJPanel.getLayout();
        layout.previous(homeJPanel);
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void btnAuthorizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAuthorizeActionPerformed
        // TODO add your handling code here:
        String name = comboStudent.getSelectedItem().toString();
        Statement statement;
        try{
            SQLiteDatabaseConnection.disconnect();
            conn = SQLiteDatabaseConnection.connect();
            conn.setAutoCommit(false);
            statement = conn.createStatement();
            String query = "SELECT personid FROM Person WHERE name = '"+name+"';";
            ResultSet rs = statement.executeQuery(query);
            int id = rs.getInt("personId");
            SQLiteDatabaseConnection.disconnect();
            conn = SQLiteDatabaseConnection.connect();
            conn.setAutoCommit(false);
            statement = conn.createStatement();
            String query1 = "INSERT INTO CERTIFICATE(issuedToStudent) VALUES ("+id+");";
            statement.execute(query1);
            conn.commit();
            SQLiteDatabaseConnection.disconnect();
            conn = SQLiteDatabaseConnection.connect();
            conn.setAutoCommit(false);
            statement = conn.createStatement();
            String query2 = "UPDATE STUDENT SET certificateIssued = 1 WHERE studentId = "+id+";";
            statement.execute(query2);
            conn.commit();
            JOptionPane.showMessageDialog(null, "Certificate Issued to the student Successfully!");
        } catch (SQLException ex) { 
            Logger.getLogger(CertificationAuthorityJPanel.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_btnAuthorizeActionPerformed

    private void ProvideCertificationPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_ProvideCertificationPanelComponentShown
        // TODO add your handling code here:
         Statement statement;
        try{
            SQLiteDatabaseConnection.disconnect();
            conn = SQLiteDatabaseConnection.connect();
            conn.setAutoCommit(false);
            statement = conn.createStatement();
            String query = "SELECT name FROM Person where personid IN( SELECT studentId FROM Student WHERE wantToGraduate = 1 AND certificateIssued = 0);";
            ResultSet rs = statement.executeQuery(query);
            while (rs.next()) {
            String item = rs.getString("name");
            comboStudent.addItem(item);
            }
        } catch (SQLException ex) { 
            Logger.getLogger(CertificationAuthorityJPanel.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_ProvideCertificationPanelComponentShown

    private void btnAuthorize1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAuthorize1ActionPerformed
        // TODO add your handling code here:
        displayStudentDetails();
    }//GEN-LAST:event_btnAuthorize1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CertificationHomePanel;
    private javax.swing.JPanel CertificationLogoPanel;
    private javax.swing.JPanel CertificationPanel;
    private javax.swing.JTabbedPane CertificationTabbedPane;
    private javax.swing.JPanel ProvideCertificationPanel;
    private javax.swing.JLabel ThirdPartyLabel;
    private javax.swing.JButton btnAuthorize;
    private javax.swing.JButton btnAuthorize1;
    private javax.swing.JComboBox<String> comboStudent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JLabel studentHomeLabel;
    private javax.swing.JTable tblCertificateCourseDisplay;
    private javax.swing.JLabel text2;
    // End of variables declaration//GEN-END:variables

    private void displayStudentDetails() {
       String name = comboStudent.getSelectedItem().toString();
        System.out.println(name);
       btnAuthorize.setEnabled(true);
       ArrayList <String> values = new ArrayList<>();
        try{
            SQLiteDatabaseConnection.disconnect();
            conn = SQLiteDatabaseConnection.connect();
            conn.setAutoCommit(false);
            Statement statement = conn.createStatement();
            String query = "SELECT DISTINCT sc.courseId, c.coursename, sc.gradepointachieved FROM StudentCourse sc \n" +
            "JOIN Person p ON p.personId = c.professorAssociated " +
            "JOIN Course c ON c.courseId = sc.courseId " +
            "WHERE sc.studentid = (SELECT personid FROM Person WHERE name = '"+name+"');";
            ResultSet resultSet = statement.executeQuery(query);
            while (resultSet.next()) {
            int Id = resultSet.getInt("courseId");
            String courseName = resultSet.getString("courseName");
            float gpa = resultSet.getFloat("gradePointAchieved");
            String record = Id + "," + courseName + "," + gpa;
            values.add(record);
            }
        } catch (SQLException ex) { 
            Logger.getLogger(CertificationAuthorityJPanel.class.getName()).log(Level.SEVERE, null, ex);
        } 
        DefaultTableModel dtm = (DefaultTableModel) tblCertificateCourseDisplay.getModel();
        dtm.setRowCount(0);
        Object[] row = new Object[4];
        for (String record : values) {
            String[] recordValues = record.split(",");
            row[0]= recordValues[0];
            row[1] = recordValues[1];
            row[2]= recordValues[2];
            dtm.addRow(row);
        }
    }
}
